[Default]

	model="logarithmic"

	[Default.metadata]
	samplerate=32000
	frequency=8000

	[Default.preprocessing]
	window="hanning"
	duration=60
	sample_length=5
	sample_number=''
	overlap=0.5
	
	[Default.parameters]
	a = 78
	b = 1.5
	c = 1



[Pensieri]

	model="quadratic"

	[Pensieri.metadata]
	samplerate=100000
	frequency=8000

	[Pensieri.preprocessing]
	window="hanning"
	duration=4.5
	sample_length=0.01024
	sample_number=8
	overlap=0.2
	
	[Pensieri.parameters]
	a = 0.044642
	b = -3.2917
	c = 63.016
	d = 0
